apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo
  labels:
    app: java-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata:
      labels:
        app: java-demo
    spec:
      initContainers:
      - name: download-jar
        image: curlimages/curl:8.4.0
        command: ['sh', '-c']
        args:
        - |
          curl -u admin:Tourn1qu3T \
            "http://jenkins.jenkins.svc.cluster.local:8080/job/java-demo-pipeline/job/main/lastSuccessfulBuild/artifact/build/libs/java-demo-pipeline_main-1.0.0.jar" \
            -o /shared/app.jar
        volumeMounts:
        - name: shared-storage
          mountPath: /shared
      containers:
      - name: java-app
        image: eclipse-temurin:17-jre
        command: ['java', '-jar', '/app/app.jar']
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: shared-storage
          mountPath: /app
      volumes:
      - name: shared-storage
        emptyDir: {}
